markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://hijiangtao.github.io
website-url: http://hijiangtao.weebly.com
name: Data.Blog
website: Austin's House
author: hijiangtao
email: hijiangtao@gmail.com
duoshuo: datablog
weibo: 1679954022
github: hijiangtao
pygments: true
safe: true
paginate: 20
about: "这里是 hijiangtao 的个人技术博客，欢迎你的到来。"
host: 0.0.0.0
port: 4000
destination: ./_site
layouts: ./_layouts